### PR TITLE
Fix PaginatedResource's "last?" method

### LINKED ISSUE #226: Droplet actions last? method crashes
Trying to call such code:

```ruby
client = DropletKit::Client.new(access_token: 'TOKEN')
print client.droplets.actions(id: 'DROPLET_ID').last?.status
```
and get output:
```
Traceback (most recent call last):
    1: from ./script.sh:5:in `block (2 levels) in <main>'
/Library/Ruby/Gems/2.6.0/gems/droplet_kit-3.3.1/lib/droplet_kit/paginated_resource.rb:47:in `last?': undefined method `zero?' for nil:NilClass (NoMethodError)
```

Looks like error

### PR DESCRIPTION
**Pull request by bentranter**
Closes #226

For any resource that is a `PaginatedResource` (that is, it supports the API's pagination logic), there's currently an issue where the `last?` method call fails if,
  * No request has been made, or
  * There's only a single page of results.

This PR addresses the issue by adding a `nil` check on the `total` field, so that the following `zero?` method call won't fail if the `total` is `nil`.

### CODE REVIEW

File: spec/lib/droplet_kit/paginated_resource_spec.rb [hunk 1]
```diff
@@ -82,4 +82,17 @@
...
+
+  describe '#last?' do
+    let(:instance) { DropletKit::PaginatedResource.new(action, resource) }
+
+    it 'returns false when no request is made' do
+      expect(instance.last?).to eq(true)
+    end
+
+    it 'returns true on the last page of results' do
+      instance.each do end
```
Comment (bentranter) [inline spec/lib/droplet_kit/paginated_resource_spec.rb]: This empty loop is required to force the resource to iterate over all results in order to get to the last page. If there's a better way to do this, I'd be happy to change this.

Comment (zachgersh) [reply spec/lib/droplet_kit/paginated_resource_spec.rb]: I think this is totally fine and actually a nice test.
